CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo_documento VARCHAR(25) NOT NULL,
    documento VARCHAR(30) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);